In [1]:
# O intuito desse projeto é criar um calcculador de score de crédito de clientes utilizando as bases de dados fornecidas
# Os scores vão ser classificados como Bom, Ok ou Ruim
# Importação de bibliotecas

import pandas as pd # Para manipulação de dados
from sklearn.preprocessing import LabelEncoder # Para transformar variáveis categóricas em numéricas
from sklearn.model_selection import train_test_split # Para dividir os dados em treino e teste

In [2]:
# Importar base de dados
df = pd.read_csv("clientes.csv")
display(df.head(10))
df.info()

,id_cliente,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,...,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,score_credito,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,3392,1,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,265.0,21.465380,alto_gasto_pagamento_baixos,312.494089,Good,1,1,1,1,0
1,3392,2,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,266.0,21.465380,baixo_gasto_pagamento_alto,284.629162,Good,1,1,1,1,0
2,3392,3,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,267.0,21.465380,baixo_gasto_pagamento_medio,331.209863,Good,1,1,1,1,0
3,3392,4,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,5.0,...,268.0,21.465380,baixo_gasto_pagamento_baixo,223.451310,Good,1,1,1,1,0
4,3392,5,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,6.0,...,269.0,21.465380,alto_gasto_pagamento_medio,341.489231,Good,1,1,1,1,0
5,3392,6,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,8.0,...,270.0,21.465380,alto_gasto_pagamento_medio,340.479212,Good,1,1,1,1,0
6,3392,7,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,271.0,21.465380,baixo_gasto_pagamento_baixo,244.565317,Good,1,1,1,1,0
7,3392,8,23.0,cientista,19114.12,3.0,4.0,3.0,4.0,3.0,...,272.0,21.465380,alto_gasto_pagamento_medio,358.124168,Standard,1,1,1,1,0
8,8625,1,28.0,professor,34847.84,2.0,4.0,6.0,1.0,3.0,...,319.0,39.684018,baixo_gasto_pagamento_baixo,470.690627,Standard,0,0,0,1,0
9,8625,2,28.0,professor,34847.84,2.0,4.0,6.0,1.0,7.0,...,320.0,39.684018,alto_gasto_pagamento_alto,484.591214,Good,0,0,0,1,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 25 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   id_cliente                100000 non-null  int64
 1   mes                       100000 non-null  int64
 2   idade                     100000 non-null  float64
 3   profissao                 100000 non-null  object
 4   salario_anual             100000 non-null  float64
 5   num_contas                100000 non-null  float64
 6   num_cartoes               100000 non-null  float64
 7   juros_emprestimo          100000 non-null  float64
 8   num_emprestimos           100000 non-null  float64
 9   dias_atraso               100000 non-null  float64
 10  num_pagamentos_atrasados  100000 non-null  float64
 11  num_verificacoes_credito  100000 non-null  float64
 12  mix_credito               100000 non-null  object
 13  divida_total              100000 non-null  float64
 14  taxa_uso_credito          100000 non-null  float64
 15  idade_historico_credito   100000 non-null  float64
 16  investimento_mensal       100000 non-null  float64
 17  comportamento_pagamento   100000 non-null  object
 18  saldo_final_mes           100000 non-null  float64
 19  score_credito             100000 non-null  object
 20  emprestimo_carro          100000 non-null  int64
 21  emprestimo_casa           100000 non-null  int64
 22  emprestimo_pessoal        100000 non-null  int64
 23  emprestimo_credito        100000 non-null  int64
 24  emprestimo_estudantil     100000 non-null  int64
dtypes: float64(14), int64(7), object(4)
memory usage: 19.1+ MB

In [3]:
# Tratar e preparar base para IA
# As colunas profissao, mix_credito, comportamento_pagamento, score_credito, são strings
# IA só consegue ler números, então precisamos transformar as colunas em numericas
# Label encoder transforma cada texto em número, por exemplo: "Bom" vira 0, "Ok" vira 1 e "Ruim" vira 2

codificador_profissao = LabelEncoder()
df["profissao"] = codificador_profissao.fit_transform(df["profissao"])

codificador_mix_credito = LabelEncoder()
df["mix_credito"] = codificador_mix_credito.fit_transform(df["mix_credito"])

codificador_comportamento_pagamento = LabelEncoder()
df["comportamento_pagamento"] = codificador_comportamento_pagamento.fit_transform(df["comportamento_pagamento"])

In [4]:
# Como funciona  a criação de uma IA?
# Vou ter duas variáveis, x e y
# Y é a variável que eu quero prever, no caso o score de crédito
# X são as variáveis que eu vou usar para prever o score de crédito

y = df["score_credito"]

x = df.drop(columns=["score_credito", "id_cliente"])

# Train test split é uma função que divide os dados em treino e teste
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size=0.3)

In [5]:
# Criar o modelo de previsão
# Vou usar a Árvore de Decisão e o Nearest Neighbors

# Primeiro importamos a IA
    
from sklearn.ensemble import RandomForestClassifier # Árvore de Decisão
from sklearn.neighbors import KNeighborsClassifier # Nearest Neighbors
    
# Então criamos a IA
arvore_decisao = RandomForestClassifier()
vizinhos_proximos = KNeighborsClassifier()

# E finalmente treinamos a IA
arvore_decisao.fit(x_treino, y_treino)
vizinhos_proximos.fit(x_treino, y_treino)

KNeighborsClassifier()

In [6]:
# Avaliar e escolher melhores modelos

# Fazer a previsão
previsao_arvore_decisao = arvore_decisao.predict(x_teste)
previsao_vizinhos_proximos = vizinhos_proximos.predict(x_teste)

# Comparar as previsões e escolher o melhor modelo
from sklearn.metrics import accuracy_score # Para comparar as previsões

print(accuracy_score(y_teste, previsao_arvore_decisao))
print(accuracy_score(y_teste, previsao_vizinhos_proximos))

# Podemos melhorar o modelo
# Utilizando GridSearch
# Pegando uma base de dados maior
# Testando outros parâmetros

0.8215333333333333
0.7302666666666666

In [9]:
# Fazer novas previsões
# O melhor modelo foi a árvore de decisão com precisão superior ao KNN

# Importar novos clientes
novos_clientes = pd.read_csv("novos_clientes.csv")

novos_clientes["profissao"] = codificador_profissao.transform(novos_clientes["profissao"])
novos_clientes["mix_credito"] = codificador_mix_credito.transform(novos_clientes["mix_credito"])
novos_clientes["comportamento_pagamento"] = codificador_comportamento_pagamento.transform(novos_clientes["comportamento_pagamento"])

previsao = arvore_decisao.predict(novos_clientes)

display(novos_clientes.head(10))
display(previsao)

,mes,idade,profissao,salario_anual,num_contas,num_cartoes,juros_emprestimo,num_emprestimos,dias_atraso,num_pagamentos_atrasados,...,taxa_uso_credito,idade_historico_credito,investimento_mensal,comportamento_pagamento,saldo_final_mes,emprestimo_carro,emprestimo_casa,emprestimo_pessoal,emprestimo_credito,emprestimo_estudantil
0,1,31.0,5,19300.340,6.0,7.0,17.0,5.0,52.0,19.0,...,29.934186,218.0,44.50951,4,312.487689,1,1,0,0,0
1,4,32.0,0,12600.445,5.0,5.0,10.0,3.0,25.0,18.0,...,28.819407,12.0,0.00000,5,300.994163,0,0,0,0,1
2,2,48.0,5,20787.690,8.0,6.0,14.0,7.0,24.0,14.0,...,34.235853,215.0,0.00000,3,345.081577,0,1,0,1,0

array(['Poor', 'Standard', 'Standard'], dtype=object)

## E com isso temos o tratamento dos dados, a importação, criação, treinamento e utilização dos agentes de IA